- name: Docker image pull and deploy
  hosts: localhost
  user: ubuntu

  tasks:
  - name: Docker image pull
    shell:
      cmd: docker pull amclau303/project:1.0

  - name: kubernetes deploy
    shell:
      cmd: kubectl create deployment kubenetes-server --image=amclau303/project:1.0
